@extends('layouts.admin.base')
@section('content')
<main class="page-body"><div class="container-xl">
    <div class="page-header mb-4"><div class="row align-items-center"><div class="col"><h1 class="page-title">Inteligência climática</h1><div class="text-secondary">Previsão por talhão e avisos para tarefas programadas.</div></div><div class="col-auto"><form method="POST" action="{{ route('admin.inteligencia.sincronizar') }}">@csrf<button class="btn btn-primary">Atualizar previsão agora</button></form></div></div></div>
    @foreach (['success' => 'success', 'error' => 'danger'] as $key => $class) @if (session($key))<div class="alert alert-{{ $class }}">{{ session($key) }}</div>@endif @endforeach
    @if ($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="alert alert-info">Fonte: Open-Meteo · horizonte horário de 7 dias. Última atualização: {{ $atualizadoEm ? \Illuminate\Support\Carbon::parse($atualizadoEm)->format('d/m/Y H:i') : 'ainda não sincronizada' }}. Previsões apoiam o planejamento e não substituem a avaliação no campo.</div>
    <div class="row row-cards mb-4"><div class="col-lg-5"><div class="card"><div class="card-header"><h2 class="card-title">Adicionar regra</h2></div><form method="POST" action="{{ route('admin.inteligencia.regras.store') }}">@csrf<div class="card-body"><div class="row g-3">
        <div class="col-12"><label class="form-label">Nome</label><input name="nome" class="form-control" maxlength="120" required value="{{ old('nome') }}"></div>
        <div class="col-md-6"><label class="form-label">Tipo de tarefa</label><select name="tipo_tarefa" class="form-select"><option value="">Qualquer tipo</option>@foreach (['aplicacao'=>'Aplicação','aracao'=>'Aração','calagem'=>'Calagem','irrigacao'=>'Irrigação','manutencao'=>'Manutenção','outro'=>'Outro'] as $v=>$label)<option value="{{ $v }}">{{ $label }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label">Variável</label><select name="variavel" class="form-select" required>@foreach (['velocidade_vento'=>'Vento (km/h)','rajada_vento'=>'Rajada (km/h)','precipitacao'=>'Precipitação (mm)','chance_chuva'=>'Chance de chuva (%)','temperatura'=>'Temperatura (°C)','umidade'=>'Umidade (%)'] as $v=>$label)<option value="{{ $v }}">{{ $label }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label">Agregação na janela</label><select name="agregacao" class="form-select"><option value="maximo">Máximo</option><option value="soma">Soma</option><option value="media">Média</option></select></div>
        <div class="col-md-6"><label class="form-label">Condição</label><select name="operador" class="form-select">@foreach (['maior'=>'Maior que','maior_igual'=>'Maior ou igual','menor'=>'Menor que','menor_igual'=>'Menor ou igual','igual'=>'Igual a'] as $v=>$label)<option value="{{ $v }}">{{ $label }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label">Limite</label><input name="valor" type="number" step="0.01" class="form-control" required></div><div class="col-md-4"><label class="form-label">Unidade</label><input name="unidade" class="form-control" placeholder="km/h, mm..."></div><div class="col-md-4"><label class="form-label">Janela (horas)</label><input name="janela_horas" type="number" min="1" max="168" value="24" class="form-control" required></div>
        <div class="col-md-4"><label class="form-label">Gravidade</label><select name="gravidade" class="form-select"><option value="baixa">Baixa</option><option value="media" selected>Média</option><option value="alta">Alta</option></select></div><div class="col-md-8"><label class="form-label">Mensagem do aviso</label><input name="mensagem" class="form-control" maxlength="1000" required></div>
        <div class="col-12"><label class="form-check"><input type="checkbox" name="ativa" value="1" checked class="form-check-input"><span class="form-check-label">Regra ativa</span></label></div>
    </div></div><div class="card-footer"><button class="btn btn-primary">Salvar regra</button></div></form></div></div>
    <div class="col-lg-7"><div class="card"><div class="card-header"><h2 class="card-title">Regras cadastradas</h2></div><div class="list-group list-group-flush">
        @forelse ($regras as $regra)<div class="list-group-item"><div class="d-flex align-items-start"><div class="flex-fill"><div class="fw-bold">{{ $regra->nome }} <span class="badge {{ $regra->ativa ? 'bg-green-lt' : 'bg-secondary-lt' }}">{{ $regra->ativa ? 'Ativa' : 'Inativa' }}</span></div><div class="text-secondary small">{{ $regra->tipo_tarefa ? ucfirst(str_replace('_',' ', $regra->tipo_tarefa)) : 'Todos os tipos' }} · {{ str_replace('_',' ', $regra->variavel) }} {{ str_replace('_',' ', $regra->operador) }} {{ $regra->valor }} {{ $regra->unidade }} · {{ $regra->agregacao }} em {{ $regra->janela_horas }} h</div><div>{{ $regra->mensagem }}</div>
            <details class="mt-2"><summary class="small">Editar regra</summary><form method="POST" action="{{ route('admin.inteligencia.regras.update', $regra) }}" class="row g-2 mt-1">@csrf @method('PATCH')
                <div class="col-md-6"><input name="nome" class="form-control form-control-sm" value="{{ $regra->nome }}" required></div><div class="col-md-6"><select name="tipo_tarefa" class="form-select form-select-sm"><option value="">Qualquer tipo</option>@foreach (['aplicacao','aracao','calagem','irrigacao','manutencao','outro'] as $tipo)<option value="{{ $tipo }}" @selected($regra->tipo_tarefa === $tipo)>{{ ucfirst(str_replace('_',' ', $tipo)) }}</option>@endforeach</select></div>
                <div class="col-md-6"><select name="variavel" class="form-select form-select-sm">@foreach (['temperatura','umidade','velocidade_vento','rajada_vento','precipitacao','chance_chuva'] as $variavel)<option value="{{ $variavel }}" @selected($regra->variavel === $variavel)>{{ str_replace('_',' ', $variavel) }}</option>@endforeach</select></div><div class="col-md-6"><select name="agregacao" class="form-select form-select-sm">@foreach (['maximo','soma','media'] as $agg)<option value="{{ $agg }}" @selected($regra->agregacao === $agg)>{{ ucfirst($agg) }}</option>@endforeach</select></div>
                <div class="col-md-3"><select name="operador" class="form-select form-select-sm">@foreach (['maior','maior_igual','menor','menor_igual','igual'] as $op)<option value="{{ $op }}" @selected($regra->operador === $op)>{{ str_replace('_',' ', $op) }}</option>@endforeach</select></div><div class="col-md-3"><input name="valor" type="number" step="0.01" class="form-control form-control-sm" value="{{ $regra->valor }}" required></div><div class="col-md-3"><input name="unidade" class="form-control form-control-sm" value="{{ $regra->unidade }}" placeholder="Unidade"></div><div class="col-md-3"><input name="janela_horas" type="number" min="1" max="168" class="form-control form-control-sm" value="{{ $regra->janela_horas }}" required></div>
                <div class="col-md-3"><select name="gravidade" class="form-select form-select-sm">@foreach (['baixa','media','alta'] as $g)<option value="{{ $g }}" @selected($regra->gravidade === $g)>{{ ucfirst($g) }}</option>@endforeach</select></div><div class="col-md-7"><input name="mensagem" class="form-control form-control-sm" value="{{ $regra->mensagem }}" required></div><div class="col-md-2"><label class="form-check"><input name="ativa" value="1" type="checkbox" class="form-check-input" @checked($regra->ativa)>Ativa</label></div><div class="col-12"><button class="btn btn-sm btn-outline-primary">Salvar alterações</button></div>
            </form></details>
        </div><form method="POST" action="{{ route('admin.inteligencia.regras.destroy', $regra) }}" onsubmit="return confirm('Remover esta regra?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remover</button></form></div></div>@empty<div class="list-group-item text-secondary">Ainda não há regras. Cadastre os limites definidos pela equipe agronômica.</div>@endforelse
    </div></div></div></div>
    <div class="card"><div class="card-header"><h2 class="card-title">Tarefas próximas</h2></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Tarefa</th><th>Local</th><th>Data</th><th>Avisos</th></tr></thead><tbody>
        @forelse ($tarefas as $tarefa)<tr><td><a href="{{ route('admin.tarefas.show', $tarefa) }}">{{ $tarefa->titulo }}</a><div class="text-secondary small">{{ ucfirst(str_replace('_',' ', $tarefa->tipo)) }}</div></td><td>{{ $tarefa->propriedade->nome }} · {{ $tarefa->talhao->nome ?? 'sem talhão' }}</td><td>{{ $tarefa->data_prevista->format('d/m/Y') }}</td><td>@if (count($tarefa->alertas_climaticos))<span class="badge bg-orange-lt">{{ count($tarefa->alertas_climaticos) }} aviso(s)</span>@elseif (!$tarefa->clima_disponivel)<span class="text-danger">Sem previsão para a janela da tarefa</span>@else<span class="text-secondary">Sem alertas pelas regras ativas</span>@endif</td></tr>@empty<tr><td colspan="4" class="text-secondary">Não há tarefas futuras com status aberto.</td></tr>@endforelse
    </tbody></table></div></div>
</div></main>
@endsection
