@extends('layouts.admin.base')
@section('content')
<main class="page-body"><div class="container-xl">
    <div class="page-header mb-4"><div><h2 class="page-title">Registro de aplicações</h2><div class="text-secondary">Histórico de aplicações realizadas e consumo de produtos.</div></div></div>
    <form method="GET" class="card card-body mb-3"><div class="row g-2 align-items-end"><div class="col-auto"><label class="form-label" for="status">Status</label><select class="form-select" name="status" id="status"><option value="">Todos</option>@foreach (['realizada' => 'Realizadas', 'planejada' => 'Planejadas', 'cancelada' => 'Canceladas'] as $key => $label)<option value="{{ $key }}" @selected(request('status') === $key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label" for="propriedade_id">Propriedade</label><select class="form-select" name="propriedade_id" id="propriedade_id"><option value="">Todas as propriedades</option>@foreach ($propriedades as $propriedade)<option value="{{ $propriedade->id }}" @selected(request('propriedade_id') == $propriedade->id)>{{ $propriedade->nome }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-primary">Filtrar</button><a href="{{ route('admin.aplicacoes.index') }}" class="btn">Limpar</a></div></div></form>
    <div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Data</th><th>Propriedade / talhão</th><th>Produto</th><th>Quantidade</th><th>Operador</th><th>Status</th><th></th></tr></thead><tbody>
        @forelse ($aplicacoes as $aplicacao)<tr><td>{{ $aplicacao->data_aplicacao->format('d/m/Y') }}{{ $aplicacao->hora_aplicacao ? ' · '.substr($aplicacao->hora_aplicacao, 0, 5) : '' }}</td><td>{{ $aplicacao->talhao->propriedade->nome }}<div class="text-secondary small">{{ $aplicacao->talhao->nome }}</div></td><td>{{ $aplicacao->produto->nome }}</td><td>{{ number_format((float)$aplicacao->dose, 3, ',', '.') }} {{ $aplicacao->produto->unidade }}</td><td>{{ $aplicacao->usuario->name }}</td><td><span class="badge bg-{{ $aplicacao->status === 'realizada' ? 'green' : ($aplicacao->status === 'cancelada' ? 'red' : 'yellow') }}-lt">{{ ucfirst($aplicacao->status) }}</span></td><td><a class="btn btn-sm" href="{{ route('admin.aplicacoes.show', $aplicacao) }}">Detalhes</a></td></tr>
        @empty<tr><td colspan="7" class="text-center text-secondary py-5">Nenhuma aplicação registrada ainda. As aplicações aparecem aqui quando o operador conclui uma tarefa de aplicação.</td></tr>@endforelse
    </tbody></table></div></div><div class="mt-3">{{ $aplicacoes->links() }}</div>
</div></main>
@endsection
